apiVersion: v1
kind: Pod
metadata:
  name: krapp
  labels:
    app: rails-puma
spec:
  containers:
    - name: krapp
      image: harshwardhan3994/krappgit:latest
      ports:
        - containerPort: 3000